type ValidationError {
  error_code: String!
  error_id: String!
  fields: [FieldError!]
}

type FieldError {
  field: String!
  errors: [String!]
}

type BaseError {
  error_code: String!
  error_id: String!
}

type Success {
  message: String!
}
