const tableNames = require('./tableNames');

module.exports = [
  tableNames.people_entity_permission,
  tableNames.role_entity_permission,
  tableNames.people_course_instance_permission,
  tableNames.role_course_instance_permission,
  tableNames.superuser,
  tableNames.attendance_data,
  tableNames.time_slot,
  tableNames.course_instance_association,
  tableNames.role_people_entity,
  tableNames.role,
  tableNames.course_instance,
  tableNames.academic_duration,
  tableNames.course,
  tableNames.entity_parent_child,
  tableNames.entity_address,
  tableNames.entity,
  tableNames.entity_type,
  tableNames.auth,
  tableNames.email,
  tableNames.people_address,
  tableNames.identifier,
  tableNames.people,
  tableNames.address,
  tableNames.state,
  tableNames.country,
  tableNames.nationality,
];
