module.exports = {
  nationality: 'nationality',
  country: 'country',
  state: 'state',
  address: 'address',
  people: 'people',
  identifier: 'identifier',
  people_address: 'people_address',
  email: 'email',
  auth: 'auth',
  entity_type: 'entity_type',
  entity: 'entity',
  entity_address: 'entity_address',
  entity_parent_child: 'entity_parent_child',
  course: 'course',
  academic_duration: 'academic_duration',
  course_instance: 'course_instance',
  role: 'role',
  role_people_entity: 'role_people_entity',
  course_instance_association: 'course_instance_association',
  attendance_data: 'attendance_data',
  superuser: 'superuser',
  people_entity_permission: 'people_entity_permission',
  role_entity_permission: 'role_entity_permission',
  people_course_instance_permission: 'people_course_instance_permission',
  role_course_instance_permission: 'role_course_instance_permission',
};
