module.exports = {
  nationality: 'nationality',
  country: 'country',
  data_type: 'data_type',
  state: 'state',
  address: 'address',
  people: 'people',
  identifier: 'identifier',
  people_address: 'people_address',
  email: 'email',
  auth: 'auth',
  field: 'field',
  people_field_value: 'people_field_value',
  entity_type: 'entity_type',
  entity_type_field: 'entity_type_field',
  entity_field_value: 'entity_field_value',
  entity: 'entity',
  entity_address: 'entity_address',
  entity_parent_child: 'entity_parent_child',
  course: 'course',
  academic_duration: 'academic_duration',
  course_instance: 'course_instance',
  role: 'role',
  role_people_entity: 'role_people_entity',
  course_instance_association: 'course_instance_association',
  attendance_data: 'attendance_data',
};
