extend type Query {
  address(id: ID): [Address!]
}

type Address {
  id: ID!
  line_1: String!
  line_2: String
  city: String!
  zipcode: String!
  state: State!
  country: Country!
  latitude: Float
  longtiude: Float
  created_at: String!
  updated_at: String!
  deleted_at: String
}
